export const mockData = {
  categories: {
    rrb: {
      image: "/rrb-ntpc.webp",
      alt: "Accounts Department Test",
      title: "RRB",
      id: "rrb",
      slug: "rrb",
      description: "Technical and engineering exams",
      subcategories: {
        "rrb-ntpc": {
          id: "tests",
          image: "/rrb-ntpc.webp",
          alt: "Accounts Department Test",
          title: "RRB NTPC",
          name: "Appendix II",
          slug: "rrb-ntpc",
          description: "Mechanical engineering concepts",
          subcategories: {
            "history": {
              id: "tests",
              image: "/rrb-ntpc.webp",
              alt: "Accounts Department Test",
              title: "RRB NTPC History",
              name: "Appendix II",
              slug: "history",
              description: "Mechanical engineering concepts",
              subcategories: {
                "ancient-history": {
                  id: "ancient-history",
                  image: "/rrb-ntpc.webp",
                  alt: "Ancient History",
                  title: "Ancient History",
                  name: "Ancient History",
                  slug: "ancient-history",
                  description: "Ancient Indian History concepts and questions",
                  tests: [
                    {
                      id: "harappa-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Ancient History Harappa Mock Test",
                      title: "Ancient History - Harappa Civilization Mock Test",
                      name: "Harappa History GS Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "20",
                      marks: "20",
                      duration: "10",
                      isSpecialMock: true,
                      route: "/mock-test/harappa",
                    },
                    {
                      id: "vedic-mock-2-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Vedic Mock 2 Mock Test",
                      title: "Vedic Mock 2 - Mock Test",
                      name: "Vedic Mock 2 Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "20",
                      marks: "20",
                      duration: "10",
                      isSpecialMock: true,
                      route: "/mock-test/vedic-mock-2",
                    },
                    {
                      id: "mahajanpad-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Mahajanapada Period Mock Test",
                      title: "Mahajanapada Period - Ancient History Mock Test",
                      name: "Mahajanapada History GS Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "20",
                      marks: "20",
                      duration: "10",
                      isSpecialMock: true,
                      route: "/mock-test/mahajanpad",
                    },
                    {
                      id: "buddhism-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Buddhism Mock Test",
                      title: "Buddhism - Ancient History Mock Test",
                      name: "Buddhism History GS Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "20",
                      marks: "20",
                      duration: "3",
                      isSpecialMock: true,
                      route: "/mock-test/buddhism",
                    },
                    {
                      id: "jainism-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Jainism Mock Test",
                      title: "Jainism - Ancient History Mock Test",
                      name: "Jainism History GS Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "20",
                      marks: "20",
                      duration: "3",
                      isSpecialMock: true,
                      route: "/mock-test/jainism",
                    },
                    {
                      id: "mauryan-empire-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Mauryan Empire Mock Test",
                      title: "Mauryan Empire - Ancient History Mock Test",
                      name: "Mauryan Empire GS Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "20",
                      marks: "20",
                      duration: "3",
                      isSpecialMock: true,
                      route: "/mock-test/mauryan-empire",
                    },
                    {
                      id: "post-mauryan-empire-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Post Mauryan Empire Mock Test",
                      title: "Post Mauryan Empire - Ancient History Mock Test",
                      name: "Post Mauryan Empire GS Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "25",
                      marks: "25",
                      duration: "3",
                      isSpecialMock: true,
                      route: "/mock-test/post-mauryan-empire",
                    },
                    {
                      id: "gupta-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Gupta Empire Mock Test",
                      title: "Gupta Empire - Ancient History Mock Test",
                      name: "Gupta Empire GS Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "25",
                      marks: "25",
                      duration: "3",
                      isSpecialMock: true,
                      route: "/mock-test/gupta",
                    },
                    {
                      id: "sangam-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Sangam Period Mock Test",
                      title: "Sangam Period - History Mock Test",
                      name: "Sangam Period GS Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "20",
                      marks: "20",
                      duration: "13",
                      isSpecialMock: true,
                      route: "/mock-test/sangam",
                    },
                  ],
                },
                "medieval-history": {
                  id: "medieval-history",
                  image: "/rrb-ntpc.webp",
                  alt: "Medieval History",
                  title: "Medieval History",
                  name: "Medieval History",
                  slug: "medieval-history",
                  description: "Medieval Indian History concepts and questions",
                  tests: [
                    {
                      id: "delhi-sultanate-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Delhi Sultanate Mock Test",
                      title: "Delhi Sultanate - Mock Test",
                      name: "Delhi Sultanate Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "20",
                      marks: "20",
                      duration: "3",
                      isSpecialMock: true,
                      route: "/mock-test/delhi-sultanate",
                    },
                    {
                      id: "vijayanagar-bahmani-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Vijayanagar and Bahmani Kingdoms Mock Test",
                      title: "Vijayanagar & Bahmani Kingdoms - History Mock Test",
                      name: "Vijayanagar Bahmani GS Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "25",
                      marks: "25",
                      duration: "13",
                      isSpecialMock: true,
                      route: "/mock-test/vijayanagar-bahmani",
                    },
                    {
                      id: "VijayNagarAndBahmani-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Vijay Nagar And Bahmani Mock Test",
                      title: "Vijay Nagar And Bahmani - Mock Test",
                      name: "Vijay Nagar And Bahmani Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "25",
                      marks: "25",
                      duration: "3",
                      isSpecialMock: true,
                      route: "/mock-test/VijayNagarAndBahmani",
                    },
                    {
                      id: "Mughal-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Mughal Mock Test",
                      title: "Mughal - Mock Test",
                      name: "Mughal Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "20",
                      marks: "20",
                      duration: "10",
                      isSpecialMock: true,
                      route: "/mock-test/Mughal",
                    },
                    {
                      id: "BhaktiAndSufi-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Bhakti And Sufi - Mock Test",
                      title: "Bhakti And Sufi - Mock Test",
                      name: "Bhakti And Sufi Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "21",
                      marks: "21",
                      duration: "3",
                      isSpecialMock: true,
                      route: "/mock-test/BhaktiAndSufi",
                    },
                    {
                      id: "Maratha-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Maratha Mock Test",
                      title: "Maratha - Mock Test",
                      name: "Maratha Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "30",
                      marks: "30",
                      duration: "3",
                      isSpecialMock: true,
                      route: "/mock-test/Maratha",
                    },
                  ],
                },
                "modern-history": {
                  id: "modern-history",
                  image: "/rrb-ntpc.webp",
                  alt: "Modern History",
                  title: "Modern History",
                  name: "Modern History",
                  slug: "modern-history",
                  description: "Modern Indian History concepts and questions",
                  tests: [
                    {
                      id: "Advent-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Advent Mock Test",
                      title: "Advent - Mock Test",
                      name: "Advent Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "15",
                      marks: "15",
                      duration: "5",
                      isSpecialMock: true,
                      route: "/mock-test/Advent",
                    },
                    {
                      id: "RevoltEconomicImpactPeasant-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Revolt Economic Impact Peasant Mock Test",
                      title: "Revolt Economic Impact Peasant - Mock Test",
                      name: "Revolt Economic Impact Peasant Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "20",
                      marks: "20",
                      duration: "3",
                      isSpecialMock: true,
                      route: "/mock-test/RevoltEconomicImpactPeasant",
                    },
                    {
                      id: "ModernHistoryExtremistPhase-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Modern History Extremist Phase Mock Test",
                      title: "Modern History Extremist Phase - Mock Test",
                      name: "Modern History Extremist Phase Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "30",
                      marks: "30",
                      duration: "5",
                      isSpecialMock: true,
                      route: "/mock-test/ModernHistoryExtremistPhase",
                    },
                  ],
                },
              },
              tests: [
                {
                  id: "hostory-full-revision-test-mock-test",
                  image: "/rrb-ntpc.webp",
                  alt: "History Full Revision Test Mock Test",
                  title: "History Full Revision Test - Mock Test",
                  name: "History Full Revision Test Mock",
                  difficulty: "Hard",
                  languages: ["English", "Hindi"],
                  questions: "100",
                  marks: "100",
                  duration: "5",
                  isSpecialMock: true,
                  route: "/mock-test/hostory-full-revision-test",
                },
              ],
            },
            "polity": {
              id: "tests",
              image: "/rrb-ntpc.webp",
              alt: "Accounts Department Test",
              title: "RRB NTPC Polity",
              name: "Appendix II",
              slug: "polity",
              description: "Mechanical engineering concepts",
              subcategories: {
                "constitution": {
                  id: "constitution",
                  image: "/rrb-ntpc.webp",
                  alt: "Constitution",
                  title: "Constitution",
                  name: "Constitution",
                  slug: "constitution",
                  description: "Indian Constitution and Framework",
                  tests: [
                    {
                      id: "PolityConstitutionAndPreambleAndSources-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Polity Constitution And Preamble And Sources Mock Test",
                      title: "Polity Constitution And Preamble And Sources - Mock Test",
                      name: "Polity Constitution And Preamble And Sources Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "20",
                      marks: "20",
                      duration: "3",
                      isSpecialMock: true,
                      route: "/mock-test/PolityConstitutionAndPreambleAndSources",
                    },
                    {
                      id: "ScheduleCitizenship-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Schedule Citizenship Mock Test",
                      title: "Schedule Citizenship - Mock Test",
                      name: "Schedule Citizenship Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "20",
                      marks: "20",
                      duration: "3",
                      isSpecialMock: true,
                      route: "/mock-test/ScheduleCitizenship",
                    },
                    {
                      id: "FundamentalRightsAndDpSp-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Fundamental Rights And DP SP Mock Test",
                      title: "Fundamental Rights And DP SP - Mock Test",
                      name: "Fundamental Rights And DP SP Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "25",
                      marks: "25",
                      duration: "4",
                      isSpecialMock: true,
                      route: "/mock-test/FundamentalRightsAndDpSp",
                    },
                    {
                      id: "Amendments-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Amendments Mock Test",
                      title: "Amendments - Mock Test",
                      name: "Amendments Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "20",
                      marks: "20",
                      duration: "3",
                      isSpecialMock: true,
                      route: "/mock-test/Amendments",
                    },
                  ],
                },
                "centre": {
                  id: "centre",
                  image: "/rrb-ntpc.webp",
                  alt: "Centre",
                  title: "Centre",
                  name: "Centre",
                  slug: "centre",
                  description: "Central Government and Executive",
                  tests: [
                    {
                      id: "Parliament-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Parliament Mock Test",
                      title: "Parliament - Mock Test",
                      name: "Parliament Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "25",
                      marks: "25",
                      duration: "3",
                      isSpecialMock: true,
                      route: "/mock-test/Parliament",
                    },
                  ],
                },
                "state": {
                  id: "state",
                  image: "/rrb-ntpc.webp",
                  alt: "State",
                  title: "State",
                  name: "State",
                  slug: "state",
                  description: "State Government and Administration",
                  tests: [],
                },
              },
            },
            "geography": {
              id: "tests",
              image: "/rrb-ntpc.webp",
              alt: "Accounts Department Test",
              title: "RRB NTPC Geography",
              name: "Appendix II",
              slug: "geography",
              description: "Mechanical engineering concepts",
              subcategories: {
                "basic-concepts": {
                  id: "basic-concepts",
                  image: "/rrb-ntpc.webp",
                  alt: "Basic Concepts",
                  title: "Basic Concepts",
                  name: "Basic Concepts",
                  slug: "basic-concepts",
                  description: "Basic Geography Concepts",
                  tests: [
                    {
                      id: "geography-basics-test-1-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Geography Basics Test 1 Mock Test",
                      title: "Geography Basics Test 1 - Mock Test",
                      name: "Geography Basics Test 1 Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "30",
                      marks: "30",
                      duration: "10",
                      isSpecialMock: true,
                      route: "/mock-test/geography-basics-test-1",
                    },
                  ],
                },
                "indian-geography": {
                  id: "indian-geography",
                  image: "/rrb-ntpc.webp",
                  alt: "Indian Geography",
                  title: "Indian Geography",
                  name: "Indian Geography",
                  slug: "indian-geography",
                  description: "Indian Geography and Physical Features",
                  tests: [],
                },
                "environment": {
                  id: "environment",
                  image: "/rrb-ntpc.webp",
                  alt: "Environment",
                  title: "Environment",
                  name: "Environment",
                  slug: "environment",
                  description: "Environment and Ecology",
                  tests: [
                    {
                      id: "environment-quiz-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Environment Quiz Mock Test",
                      title: "Environment & Ecology - GS Mock Test",
                      name: "Environment Quiz GS Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "25",
                      marks: "25",
                      duration: "3",
                      isSpecialMock: true,
                      route: "/mock-test/environment-quiz",
                    },
                  ],
                },
              },
            },
            "science": {
              id: "tests",
              image: "/rrb-ntpc.webp",
              alt: "Accounts Department Test",
              title: "RRB NTPC Science",
              name: "Appendix II",
              slug: "science",
              description: "Mechanical engineering concepts",
              subcategories: {
                "physics": {
                  id: "physics",
                  image: "/rrb-ntpc.webp",
                  alt: "Physics",
                  title: "Physics",
                  name: "Physics",
                  slug: "physics",
                  description: "General Physics Concepts and Questions",
                  tests: [],
                },
                "chemistry": {
                  id: "chemistry",
                  image: "/rrb-ntpc.webp",
                  alt: "Chemistry",
                  title: "Chemistry",
                  name: "Chemistry",
                  slug: "chemistry",
                  description: "General Chemistry Concepts and Questions",
                  tests: [],
                },
                "biology": {
                  id: "biology",
                  image: "/rrb-ntpc.webp",
                  alt: "Biology",
                  title: "Biology",
                  name: "Biology",
                  slug: "biology",
                  description: "General Biology Concepts and Questions",
                  tests: [],
                },
              },
            },
            "maths": {
              id: "tests",
              image: "/rrb-ntpc.webp",
              alt: "Accounts Department Test",
              title: "RRB NTPC Maths",
              name: "Appendix II",
              slug: "maths",
              description: "Mechanical engineering concepts",
              subcategories: {
                "arithmetic": {
                  id: "arithmetic",
                  image: "/rrb-ntpc.webp",
                  alt: "Arithmetic",
                  title: "Arithmetic",
                  name: "Arithmetic",
                  slug: "arithmetic",
                  description: "Arithmetic Mathematics",
                  tests: [
                    {
                      id: "profit-loss-discount-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Profit Loss Discount Mock Test",
                      title: "Profit, Loss & Discount - Math Mock Test",
                      name: "Profit Loss Discount Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "35",
                      marks: "35",
                      duration: "30",
                      isSpecialMock: true,
                      route: "/mock-test/profit-loss-discount",
                    },
                    {
                      id: "Profit-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Profit Mock Test",
                      title: "Profit - Mock Test",
                      name: "Profit Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "35",
                      marks: "35",
                      duration: "30",
                      isSpecialMock: true,
                      route: "/mock-test/Profit",
                    },
                    {
                      id: "Percentage-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Percentage Mock Test",
                      title: "Percentage - Mock Test",
                      name: "Percentage Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "30",
                      marks: "30",
                      duration: "20",
                      isSpecialMock: true,
                      route: "/mock-test/Percentage",
                    },
                    {
                      id: "Ratio-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Ratio Mock Test",
                      title: "Ratio - Mock Test",
                      name: "Ratio Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "30",
                      marks: "30",
                      duration: "10",
                      isSpecialMock: true,
                      route: "/mock-test/Ratio",
                    },
                    {
                      id: "average-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Average Mock Test",
                      title: "Average - Quantitative Aptitude Mock Test",
                      name: "Average Math Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "20",
                      marks: "20",
                      duration: "3",
                      isSpecialMock: true,
                      route: "/mock-test/average",
                    },
                    {
                      id: "Average-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Average Mock Test",
                      title: "Average - Mock Test",
                      name: "Average Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "20",
                      marks: "20",
                      duration: "10",
                      isSpecialMock: true,
                      route: "/mock-test/Average",
                    },
                    {
                      id: "mixture-alligation-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Mixture & Alligation Mock Test",
                      title: "Mixture & Alligation - Math Mock Test",
                      name: "Mixture Alligation Math Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "10",
                      marks: "10",
                      duration: "10",
                      isSpecialMock: true,
                      route: "/mock-test/mixture-alligation",
                    },
                    {
                      id: "compound-interest-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Compound Interest Mock Test",
                      title: "Compound Interest - Mock Test",
                      name: "Compound Interest Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "20",
                      marks: "20",
                      duration: "10",
                      isSpecialMock: true,
                      route: "/mock-test/compound-interest",
                    },
                    {
                      id: "TimeAndWork-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Time And Work Mock Test",
                      title: "Time And Work - Mock Test",
                      name: "Time And Work Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "25",
                      marks: "25",
                      duration: "20",
                      isSpecialMock: true,
                      route: "/mock-test/TimeAndWork",
                    },
                    {
                      id: "pipe-cistern-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Pipe Cistern Mock Test",
                      title: "Pipe Cistern - Mock Test",
                      name: "Pipe Cistern Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "30",
                      marks: "30",
                      duration: "10",
                      isSpecialMock: true,
                      route: "/mock-test/pipe-cistern",
                    },
                    {
                      id: "Pipe-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Pipe Mock Test",
                      title: "Pipe - Mock Test",
                      name: "Pipe Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "30",
                      marks: "30",
                      duration: "10",
                      isSpecialMock: true,
                      route: "/mock-test/Pipe",
                    },
                    {
                      id: "TimeSpeedDistanceBoat-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Time Speed Distance Boat Mock Test",
                      title: "Time Speed Distance Boat - Mock Test",
                      name: "Time Speed Distance Boat Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "30",
                      marks: "30",
                      duration: "30",
                      isSpecialMock: true,
                      route: "/mock-test/TimeSpeedDistanceBoat",
                    },
                    {
                      id: "hcf-lcm-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "HCF & LCM Mock Test",
                      title: "HCF & LCM - Mathematics Mock Test",
                      name: "HCF LCM Math Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "20",
                      marks: "20",
                      duration: "10",
                      isSpecialMock: true,
                      route: "/mock-test/hcf-lcm",
                    },
                    {
                      id: "ArithmeticSectionalTest-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Arithmetic Sectional Test Mock Test",
                      title: "Arithmetic Sectional Test - Mock Test",
                      name: "Arithmetic Sectional Test Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "30",
                      marks: "30",
                      duration: "15",
                      isSpecialMock: true,
                      route: "/mock-test/ArithmeticSectionalTest",
                    },
                  ],
                },
                "advanced": {
                  id: "advanced",
                  image: "/rrb-ntpc.webp",
                  alt: "Advanced",
                  title: "Advanced",
                  name: "Advanced",
                  slug: "advanced",
                  description: "Advanced Mathematics",
                  tests: [],
                },
              },
              tests: [
                {
                  id: "Maths-mock-test",
                  image: "/rrb-ntpc.webp",
                  alt: "Maths Arithmetic Revision Test Mock Test",
                  title: "Maths Arithmetic Revision Test - Mock Test",
                  name: "Maths Arithmetic Revision Test",
                  difficulty: "Hard",
                  languages: ["English", "Hindi"],
                  questions: "130",
                  marks: "130",
                  duration: "90",
                  isSpecialMock: true,
                  route: "/mock-test/Maths",
                },
              ],
            },
            "economy": {
              id: "tests",
              image: "/rrb-ntpc.webp",
              alt: "RRB NTPC Economy",
              title: "RRB NTPC Economy",
              name: "Appendix II",
              slug: "economy",
              description: "Economics concepts and questions",
              subcategories: {
                "basic-concepts": {
                  id: "basic-concepts",
                  image: "/rrb-ntpc.webp",
                  alt: "Basic Concepts",
                  title: "Basic Concepts",
                  name: "Basic Concepts",
                  slug: "basic-concepts",
                  description: "Basic Economics Concepts and Fundamentals",
                  tests: [],
                },
                "banking-and-taxation": {
                  id: "banking-and-taxation",
                  image: "/rrb-ntpc.webp",
                  alt: "Banking and Taxation",
                  title: "Banking and Taxation",
                  name: "Banking and Taxation",
                  slug: "banking-and-taxation",
                  description: "Banking System, Monetary Policy and Taxation",
                  tests: [],
                },
                "world-economy": {
                  id: "world-economy",
                  image: "/rrb-ntpc.webp",
                  alt: "World Economy",
                  title: "World Economy",
                  name: "World Economy",
                  slug: "world-economy",
                  description: "Global Economy, Trade and International Organizations",
                  tests: [],
                },
              },
            },
            "computer": {
              id: "tests",
              image: "/rrb-ntpc.webp",
              alt: "Accounts Department Test",
              title: "RRB NTPC Computer",
              name: "Appendix II",
              slug: "computer",
              description: "Mechanical engineering concepts",
              tests: [],
            },
            "current-affairs": {
              id: "tests",
              image: "/rrb-ntpc.webp",
              alt: "Accounts Department Test",
              title: "RRB NTPC Current Affairs",
              name: "Appendix II",
              slug: "current-affairs",
              description: "Mechanical engineering concepts",
              tests: [
                    {
                      id: "military-exercise-test-1-mock-test",
                      image: "/rrb-ntpc.webp",
                      alt: "Military Exercise Test 1 Mock Test",
                      title: "Military Exercise Test 1 - Mock Test",
                      name: "Military Exercise Test 1 Mock",
                      difficulty: "Hard",
                      languages: ["English", "Hindi"],
                      questions: "30",
                      marks: "30",
                      duration: "20",
                      isSpecialMock: true,
                      route: "/mock-test/military-exercise-test-1",
                    },
                  ],
            },

          },

          // tests: [
          //   {
          //     id: "5062025-1",
          //     image:
          //       "https://snwallah.com/assets/categories/7bb60bd5d40c5422e282de3c440954ef.png",
          //     alt: "Accounts Department Test",
          //     title: "RRB NTPC (UG): Shift-1 (05 June 2025)",
          //     name: "5th June 1st Shift",
          //     difficulty: "Medium",
          //     languages: ["English"],
          //     questions: "100",
          //     marks: "100",
          //     duration: "90",
          //   },
          //   {
          //     id: "5062025-3",
          //     image:
          //       "https://snwallah.com/assets/categories/7bb60bd5d40c5422e282de3c440954ef.png",
          //     alt: "Accounts Department Test",
          //     title: "RRB NTPC (UG): Shift-3 (05 June 2025)",
          //     name: "5th June 3rd Shift",
          //     difficulty: "Medium",
          //     languages: ["English"],
          //     questions: "100",
          //     marks: "100",
          //     duration: "90",
          //   },
          //   {
          //     id: "revision-test-1",
          //     image: "/rrb-ntpc.webp",
          //     alt: "Revision Test 1 Mock Test",
          //     title: "Revision Test 1 Mock Test",
          //     name: "Revision Test 1 Mock",
          //     difficulty: "Hard",
          //     languages: ["English", "Hindi"],
          //     questions: "100",
          //     marks: "100",
          //     duration: "80",
          //     isSpecialMock: true,
          //     route: "/mock-test/revision-test-1",
          //   },
          //   {
          //     id: "revision-test-2",
          //     image: "/rrb-ntpc.webp",
          //     alt: "Revision Test 2 Mock Test",
          //     title: "Revision Test 2 Mock Test",
          //     name: "Revision Test 2 Mock",
          //     difficulty: "Hard",
          //     languages: ["English", "Hindi"],
          //     questions: "100",
          //     marks: "100",
          //     duration: "80",
          //     isSpecialMock: true,
          //     route: "/mock-test/revision-test-2",
          //   },
          //   {
          //     id: "Revision-mock-test",
          //     image: "/rrb-ntpc.webp",
          //     alt: "Revision Mock Test",
          //     title: "Revision - Mock Test",
          //     name: "Revision Mock",
          //     difficulty: "Hard",
          //     languages: ["English", "Hindi"],
          //     questions: "100",
          //     marks: "100",
          //     duration: "80",
          //     isSpecialMock: true,
          //     route: "/mock-test/Revision",
          //   },
          //   {
          //     id: "Revision-Test-3-mock-test",
          //     image: "/rrb-ntpc.webp",
          //     alt: "Revision Test 3 Mock Test",
          //     title: "Revision Test 3 - Mock Test",
          //     name: "Revision Test 3 Mock",
          //     difficulty: "Hard",
          //     languages: ["English", "Hindi"],
          //     questions: "100",
          //     marks: "100",
          //     duration: "80",
          //     isSpecialMock: true,
          //     route: "/mock-test/Revision-Test-3",
          //   },
          // ],
        },
      },
    },
    rrc: {
      image: "/rrb-ntpc.webp",
      alt: "Accounts Department Test",
      title: "RRC",
      id: "rrc",
      slug: "rrc",
      description: "Technical and engineering exams",
      subcategories: {
        "rrc-group-d": {
          id: "tests",
          image: "/rrb-ntpc.webp",
          alt: "Accounts Department Test",
          title: "RRC Group D",
          name: "Appendix II",
          slug: "rrc-group-d",
          description: "Mechanical engineering concepts",
          tests: [
            {
              id: "rrc-17082022-01",
              image:
                "https://snwallah.com/assets/categories/7bb60bd5d40c5422e282de3c440954ef.png",
              alt: "Accounts Department Test",
              title: "RRC Group-D Shift-1 (17 Auguest 2025)",
              name: "5th June 3rd Shift",
              languages: ["English"],
              difficulty: "Medium",
              questions: "50",
              marks: "50",
              duration: "25",
            },
            {
              id: "rca-gs-test-1",
              image:
                "https://snwallah.com/assets/categories/7bb60bd5d40c5422e282de3c440954ef.png",
              alt: "Accounts Department Test",
              title: "General Science-Miscellaneous PYQ",
              name: "5th June 1st Shift",
              difficulty: "Medium",
              questions: "50",
              languages: ["English"],
              marks: "50",
              duration: "25",
            },
            {
              id: "rcc-physics-msc-1",
              image:
                "https://snwallah.com/assets/categories/7bb60bd5d40c5422e282de3c440954ef.png",
              alt: "Accounts Department Test",
              title: "RRC Physics Miscellaneous",
              name: "5th June 3rd Shift",
              difficulty: "Medium",
              questions: "50",
              languages: ["English"],
              marks: "50",
              duration: "60",
            }, //rrc-17082022-01
          ],
        },
      },
    },
  },
};

export const courseMockData = [
  {
    id: "course-rrb-ntpc-foundation",
    title: "Computer|RRB NTPC|SSC|Railway",
    description:
      "Build strong fundamentals for RRB NTPC with concept-focused lessons, practice support, and structured preparation guidance.",
    thumbnail:
      "https://i.ytimg.com/vi/EaTwYxmEcJs/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDDu-d9NQziCPIpQF8xdvsPzUc3Lg",
    thumbnailAlt: "RRB NTPC Foundation Course thumbnail",
    category: "Railway Exams",
    level: "Beginner",
    slug: "rrb-ntpc-foundation",
    fullDescription:
      "After analysing PYQ of RRB NTPC for Graduate and Undergraduate these lectures are RAMBAN for beginners and Veterans.Aaplog bahot ache se padhiye inko and concepts ko acha kijiye apne.",
    seasons: [
      {
        id: "season-1",
        title: "Computer",
        videos: [
          {
            id: "Lesson-01",
            episodeNumber: "Lesson-01",
            title: "Computer for All Government Exams Lecture -1",
            description:
              "Learn how to use MS Excel and MS Powerpoint effectively for your computer exams.",

            youtubeId: "UAoRvp7iU9s",
            duration: "17:48",
          },
          {
            id: "Lesson-02",
            episodeNumber: "Lesson-02",
            title: "Computer for All Government Exams Lecture -2",
            description:
              "Learn how to use MS Excel and MS Powerpoint effectively for your computer exams.",

            youtubeId: "jpdDV_ZImXs",
            duration: "22:18",
          },
          {
            id: "Lesson-03",
            episodeNumber: "Lesson-03",
            title:
              "Computer|MS Office||MS WordComputer|Operating System|Lecture -3",
            description:
              "Learn how to use MS Excel and MS Powerpoint effectively for your computer exams.",
            youtubeId: "1iApXL8iuko",
            duration: "13:27",
          },
          {
            id: "Lesson-04",
            episodeNumber: "Lesson-04",
            title: "Computer|Operating System|Lecture -4|Railway|SSC",
            description:
              "Learn how to use MS Excel and MS Powerpoint effectively for your computer exams.",
            youtubeId: "M-VXlMlmRik",
            duration: "13:47",
          },
          {
            id: "Lesson-05",
            episodeNumber: "Lesson-05",
            title: "Computer|MS Office||MS Powerpoint",
            description:
              "Learn how to use MS Excel and MS Powerpoint effectively for your computer exams.",

            youtubeId: "IwKuLAiifKw",
            duration: "12:10",
          },
          {
            id: "Lesson-06",
            episodeNumber: "Lesson-06",
            title: "Computer|MS Office|MS Excel|",
            description:
              "Learn how to use MS Office effectively for your computer exams.",

            youtubeId: "oZ8TPlLGXEY",
            duration: "11:46",
          },
          {
            id: "Lesson-07",
            episodeNumber: "Lesson-07",
            title: "Computer|PYQ|MS Word",
            description:
              "Prepare for the RRB NTPC Foundation exam by learning about computer basics, including MS Word.",
            youtubeId: "EaTwYxmEcJs",
            duration: "14:35",
          },
        ],
      },
      // {
      //   id: "season-2",
      //   title: "Season 2",
      //   videos: [
      //     {
      //       id: "ep-05",
      //       episodeNumber: "EP-05",
      //       title: "General Science - Physics 🔬 & Basic Concepts",
      //       description:
      //         "Explore fundamental physics concepts and their applications in the General Science section.",
      //       youtubeId: "ZvbzSrg0afE",
      //       duration: "30:10",
      //       completed: false,
      //     },
      //     {
      //       id: "ep-06",
      //       episodeNumber: "EP-06",
      //       title: "General Science - Chemistry ⚗️ & Reactions",
      //       description:
      //         "Learn essential chemistry topics including chemical reactions, periodic table, and compounds.",
      //       youtubeId: "iLWTnMzWtj4",
      //       duration: "27:35",
      //       completed: false,
      //     },
      //   ],
      // },
    ],
  },
  // {
  //   id: "course-rrc-group-d-complete",
  //   title: "RRC Group D Complete Course",
  //   description:
  //     "Prepare for RRC Group D with topic-wise learning modules, revision support, and exam-oriented coverage.",
  //   thumbnail: "/rrc-group-D.png",
  //   thumbnailAlt: "RRC Group D Complete Course thumbnail",
  //   category: "Railway Exams",
  //   level: "Intermediate",
  //   slug: "rrc-group-d-complete",
  //   fullDescription:
  //     "Complete preparation course for RRC Group D examination covering all subjects with detailed explanations.",
  //   seasons: [
  //     {
  //       id: "season-1",
  //       title: "Season 1",
  //       videos: [
  //         {
  //           id: "ep-01",
  //           episodeNumber: "EP-01",
  //           title: "RRC Group D Overview 🚂 & Preparation Strategy",
  //           description: "Complete overview of RRC Group D exam and effective preparation strategies.",
  //           youtubeId: "W6NZfCO5SIk",
  //           duration: "18:45",
  //           completed: false,
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   id: "course-general-science-masterclass",
  //   title: "General Science Masterclass",
  //   description:
  //     "Strengthen your General Science preparation through concise lessons, visual explanations, and targeted exam practice.",
  //   thumbnail: "/govt-exam.png",
  //   thumbnailAlt: "General Science Masterclass thumbnail",
  //   category: "Subject Course",
  //   level: "All Levels",
  //   slug: "general-science-masterclass",
  //   fullDescription:
  //     "Master General Science with this comprehensive course covering Physics, Chemistry, and Biology topics.",
  //   seasons: [
  //     {
  //       id: "season-1",
  //       title: "Season 1",
  //       videos: [
  //         {
  //           id: "ep-01",
  //           episodeNumber: "EP-01",
  //           title: "Introduction to General Science 📚 & Study Plan",
  //           description: "Learn how to approach General Science preparation systematically.",
  //           youtubeId: "uDwSnnhl-Ng",
  //           duration: "20:00",
  //           completed: false,
  //         },
  //       ],
  //     },
  //   ],
  // },
];
